### ISSUE TITLE
README on npmjs.com is outdated

### ISSUE THREAD

**Issue by ko-dever** [cprecioso/parcel-plugin-purgecss#2]
Hello.

The README on [your page on npmjs.com](https://www.npmjs.com/package/parcel-plugin-purgecss) seems outdated, see the section `Installation` :
```sh
npm install parcel-plugin-purifycss
```

I create this issue as I can't make a PR for npmjs.com 🙂 . (I saw PR #1 already fixed that for this repo)

**Comment by cprecioso** [comment]
Thanks!
