### ISSUE TITLE
Not purge  unused CSS

### ISSUE THREAD

**Issue by SoyDiego** [cprecioso/parcel-plugin-purgecss#50]
Hi, I'm testing the plugin and i have the next .scss:

```body{
  background-color: hotpink;
}

h1{

}

span{
  color: red;
}

h4{
  color: black;
}
```

and when i do `npm run build` the CSS is purged but only the empty `h1` and not the other classes (`span` and `h4` in my index.html i'm not using it).

This is the code after build: 
`body{background-color:#ff69b4}span{color:red}h4{color:#000}`.

How can I purge all my css (unused and empty classes) ??

Thanks

**Comment by cprecioso** [comment]
I lack the information to help you. What configuration are you using?

**Comment by SoyDiego** [comment]
> I lack the information to help you. What configuration are you using?

Thanks for your reply @cprecioso.
I'm using the configuration that you wrote in the README file.

purgecss.config.js
```
module.exports = {
  content: ["**/*.html"],
  css: ['*.scss'],
  whitelist: ["my-very-special-class"]
};```

and my package.json

```
{
	"name": "test",
	"version": "1.0.0",
	"description": "",
	"main": "index.js",
	"scripts": {
		"build": "parcel build ./index.html --no-source-maps --detailed-report --log-level 4",
		"build.dev": "parcel serve ./index.html --host=localhost --port=8000 !--open --log-level 4"
	},
	"keywords": [],
	"author": "",
	"license": "ISC",
	"devDependencies": {
		"parcel-bundler": "^1.12.4",
		"parcel-plugin-purgecss": "^2.1.3",
		"sass": "^1.26.7"
	}
}
```

Thanks

**Comment by cprecioso** [comment]
I just released a new version with the new major PurgeCSS, can you check if it works for you?

*package.json*:

```diff
-		"parcel-plugin-purgecss": "^2.1.3",
+		"parcel-plugin-purgecss": "^3.0.0",
```

**Comment by SoyDiego** [comment]
> I just released a new version with the new major PurgeCSS, can you check if it works for you?
> 
> _package.json_:
> 
> ```diff
> -		"parcel-plugin-purgecss": "^2.1.3",
> +		"parcel-plugin-purgecss": "^3.0.0",
> ```

Hi @cprecioso, i checked again updating your plugin but i getted the same result as before.
I have created this Sandbox https://codesandbox.io/s/testing-parcel-plugin-purgecss-zixwq, you can check, maybe i'm writting or doing something wrong.

**Index.html**
![imagen](https://user-images.githubusercontent.com/19764334/83529227-57c43380-a4ea-11ea-99d5-d9b6a5178306.png)

**src/style.scss**:
![imagen](https://user-images.githubusercontent.com/19764334/83529041-1af83c80-a4ea-11ea-982d-94ce964fbc32.png)

And this is my final result **only remove h1**:
![imagen](https://user-images.githubusercontent.com/19764334/83529122-35321a80-a4ea-11ea-99b0-7023c292645a.png).

Thanks for reading!

**Comment by cprecioso** [comment]
Got it, the glob in the `purgecss.config.js` file includes `node_modules`, so all these files are being included:

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/511681/83620499-b2fb3200-a58d-11ea-8548-49d0d7414d24.png">

This change will solve the problem

**purgecss.config.js:**
```diff
-  content: ["**/*.html"],
+  content: ["index.html"],
```

**Comment by SoyDiego** [comment]
> Got it, the glob in the `purgecss.config.js` file includes `node_modules`, so all these files are being included:
> 
> <img alt="image" width="1298" src="https://user-images.githubusercontent.com/511681/83620499-b2fb3200-a58d-11ea-8548-49d0d7414d24.png">
> 
> This change will solve the problem
> 
> **purgecss.config.js:**
> 
> ```diff
> -  content: ["**/*.html"],
> +  content: ["index.html"],
> ```

Thanks for your help @cprecioso, now works perfectly!! :)

**Comment by sergiojunene** [comment]
Es el material que hice yo no? La forma de llamarlo y el `index.html`
