### ISSUE TITLE
Growing pains

### ISSUE THREAD

**Issue by millette** [cprecioso/parcel-plugin-purgecss#7]
I'm trying out parcel, first time user.

I've been using purgecss with nextjs et gatsby and find it's great. So I gave this a shot.

You'll find my demo here (purgecss-plugin branch):
<https://github.com/millette/alain-bulma-parcel/tree/purgecss-plugin>

In short, my css (based on bulma) grows from 164 KiB to 198 KiB when I enable this plugin. After taking a closer look, the difference in size relates to css minification. When the purgecss plugin is enabled, minification doesn't happen so it appears larger.

## With purgecss:
```
dist/main.b25fc2d4.map          396.83 KB     144ms
dist/bulma.c57f01bc.css         198.23 KB     893ms
dist/main.b25fc2d4.js            87.96 KB    14.94s
dist/bulma-logo.e18c6a8a.png     10.91 KB     625ms
dist/index.html                   6.52 KB     4.90s
dist/bulma.c57f01bc.map              97 B      12ms
```

## Without purgecss:
```
dist/main.b25fc2d4.map          396.83 KB     197ms
dist/bulma.288e7a4e.css         164.42 KB    10.24s
dist/main.b25fc2d4.js            87.96 KB    22.22s
dist/bulma-logo.e18c6a8a.png     10.91 KB     662ms
dist/index.html                   6.52 KB     4.58s
dist/bulma.288e7a4e.map              97 B      76ms
```

**Comment by millette** [comment]
I also tried using the bulma sass and had the same result. Nothing is purged and css minification doesn't happen.

**Comment by cprecioso** [comment]
I'm checking your project and it indeed isn't transforming correctly.

1. The `transform` overrides Parcel's default CSS `transform` (which is the minification step), even though I'm calling 'super.transform()`

2. The `transform` is being called for each asset (and usually doesn't find the config options), which is not what we want, but calling it on the final bundle.

Fixing 2 would make 1 meaningless. But you can blame this on `parcel`'s lack of plugin documentation. And a bit hastily written plugin 😅.

I'm on it.

**Comment by cprecioso** [comment]
I'm closing this issue in favor of #8 and #9 . I will ping you once I close them both.

**Comment by millette** [comment]
Works perfectly now, went from 165 KiB (minified) to 20 KiB now. Thanks a lot!
